name: CI

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - '.github/workflows/ci.yaml'
  pull_request:
    branches:
      - main
    paths:
      - 'src/**'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Checkout GSOTS3D
        uses: actions/checkout@v4
        with:
          repository: 'benc-uk/gsots3d'
          path: './temp/gsots3d'
          ref: 'main'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install GSOTS3D
        run: npm install './temp/gsots3d'

      - name: Install dependencies
        run: npm ci

      - name: Run lint & format check
        run: |
          npm run lint
          npm run format:check
